name: SeqAn3 CI

on:
  push:
    branches:
      # Push events to branches matching refs/heads/master
      - 'master'
      # Push events to branches matching refs/heads/release*
      - 'release*'
  pull_request:

env:
  DOXYGEN_VERSION: 1.9.1
  SEQAN3_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -ex {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Documentation"
            os: ubuntu-20.04
            cmake: 3.8.2
            requires_toolchain: false
            requires_ccache: false
            build: documentation
            test_threads: 2
            skip_build_tests: true
            skip_run_tests: true ##

    steps:
      - name: Do nothing
        run: exit 0

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Send dispatch
        run: |
          curl -sSL -X POST -G -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H 'content-type: application/json' -d '{"ref":"${{ env.GITHUB_REF_SLUG}}"}' https://api.github.com/repos/${{ github.repository }}/actions/workflows/test.yml/dispatches

      - name: Send dispatch
        run: |
          curl -sSL -X POST -G -H "Accept: application/vnd.github.v3+json" -d '{"ref":"${{ env.GITHUB_REF_SLUG}}"}' https://api.github.com/repos/${{ github.repository }}/actions/workflows/test.yml/dispatches
