# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Documentation

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

env:
  SEQAN3_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    name: Documentation
    runs-on: ubuntu-latest
    if: github.repository_owner == 'eseiler'
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Doxygen
        uses: seqan/actions/setup-doxygen@main
        with:
          doxygen: 1.9.8

      - name: Configure tests
        run: |
          mkdir build && cd build
          cmake ../test/documentation
          make download-cppreference-doxygen-web-tag

      - name: Run tests
        working-directory: build
        run: ctest . -j --output-on-failure

      - name: Deploy Preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: eseiler/seqan3/composite/deploy_preview@infra/preview
        with:
          source_path_user_doc: build/doc_usr/html
          source_path_dev_doc: build/doc_dev/html
          deploy_base_path: ${{ secrets.REMOTE_PREVIEW_TARGET }}
          deploy_host: ${{ secrets.DEPLOY_HOST }}
          deploy_user: ${{ secrets.REMOTE_USER }}
          deploy_ssh_key: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
          token: ${{ secrets.TEST_PAT }}
