# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Documentation

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

env:
  SEQAN3_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    name: Documentation
    runs-on: ubuntu-latest
    if: github.repository_owner == 'eseiler'
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Doxygen
        uses: seqan/actions/setup-doxygen@main
        with:
          doxygen: 1.9.8

      - name: Configure tests
        run: |
          mkdir build && cd build
          cmake ../test/documentation
          make download-cppreference-doxygen-web-tag

      - name: Run tests
        working-directory: build
        run: ctest . -j --output-on-failure

      - name: Deploy Preview
        uses: eseiler/seqan3/composite/deploy_preview@infra/preview
        with:
          source_path_user_doc: build/doc_usr/html
          source_path_dev_doc: build/doc_dev/html
          deploy_base_path: ${{ secrets.REMOTE_PREVIEW_TARGET }}
          deploy_host: ${{ secrets.DEPLOY_HOST }}
          deploy_user: ${{ secrets.REMOTE_USER }}
          deploy_ssh_key: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
          pat: ${{ secrets.TEST_PAT }}

      # - name: Package Preview
      #   run: |
      #     mkdir -p preview/{usr,dev}
      #     mv build/doc_usr/html preview/usr/
      #     mv build/doc_dev/html preview/dev/
      #     cp .github/workflows/preview/index.html preview/
      #     cp .github/workflows/preview/style.css preview/

      # - name: Deploy Preview
      #   uses: burnett01/rsync-deployments@7.0.1
      #   with:
      #     switches: '-zr --delete --timeout=60 --omit-dir-times --mkpath'
      #     path: 'preview/'
      #     remote_path: '${{ secrets.REMOTE_PREVIEW_TARGET }}/${{ github.event.pull_request.number || github.actor }}'
      #     remote_host: ${{ secrets.DEPLOY_HOST }}
      #     remote_user: ${{ secrets.REMOTE_USER }}
      #     remote_key: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
