# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Documentation

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - unlabeled
  workflow_dispatch:

concurrency:
  group: documentation-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  SEQAN3_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    name: Documentation
    runs-on: ubuntu-latest
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'lint'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Doxygen
        uses: seqan/actions/setup-doxygen@main
        with:
          doxygen: 1.9.8

      - name: Configure tests
        run: |
          mkdir build && cd build
          cmake ../test/documentation
          make download-cppreference-doxygen-web-tag

      - name: Run tests
        working-directory: build
        run: ctest . -j --output-on-failure

      - name: Package Preview
        run: |
          mkdir -p preview/{usr,dev}
          mv build/doc_user/html preview/usr/
          mv build/doc_dev/html preview/dev/
          cp .github/preview/index.html preview/
          cp .github/preview/style.css preview/

      - name: Deploy Preview
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_PREVIEW_TARGET }}
        with:
          flags: '-zr --delete --timeout=60 --omit-dir-times'
          src: 'preview/'
          dest: '$REMOTE_USER@$REMOTE_HOST:$TARGET/${{ github.event.pull_request.number || github.ref }}'

