# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Unit Linux

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - unlabeled
  workflow_dispatch:

concurrency:
  group: linux-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  SEQAN3_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.compiler }} ${{ matrix.build_type }} ${{ matrix.unity_test }}
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'lint'
    strategy:
      fail-fast: false
      matrix:
        compiler: ["clang-19", "gcc-14"]
        build_type: ['Release', 'Debug']
        unity_test: ['ON', 'OFF']
    container:
      image: ghcr.io/seqan/${{ matrix.compiler }}
      volumes:
        - /home/runner:/home/runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure tests
        run: |
          mkdir build && cd build
          cmake ../test/unit -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                             -DCMAKE_CXX_FLAGS="-std=c++23" \
                             -DCMAKE_UNITY_BUILD=${{ matrix.unity_test }} \
                             -DCMAKE_UNITY_BUILD_BATCH_SIZE=16

      - name: Build tests
        working-directory: build
        run: |
          ccache -z
          make -k
          ccache -svvx

      - name: Run tests
        working-directory: build
        run: ctest . -j --output-on-failure --no-tests=error

