# SPDX-FileCopyrightText: 2006-2025 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Debian

on:
  schedule:
    - cron: "0 1 * * THU"
  workflow_dispatch:

concurrency:
  group: debian-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Europe/Berlin
  DEBIAN_FRONTEND: noninteractive

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    name: Debian
    runs-on: ubuntu-latest
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
    container:
      image: debian:unstable
    steps:
      - name: Install Essentials
        run: |
          mkdir -p unstable/seqan3
          apt-get update
          apt-get install --yes --no-install-recommends build-essential git cmake wget fakeroot ca-certificates autopkgtest &>unstable/apt.essentials.log

      - name: Create Source Package
        id: source_package
        run: |
          mkdir source && cd source
          git clone --depth 1 https://github.com/seqan/seqan3.git
          mkdir package && cd package
          cmake ../seqan3
          make package_source
          path=$(find "${PWD}" -maxdepth 1 -type f -name "*-Source.tar.xz")
          echo "path=${path}" >> $GITHUB_OUTPUT

      - name: Create Debian Repo
        working-directory: unstable
        run: |
          tar xf ${{ steps.source_package.outputs.path }} -C seqan3 --strip-components=1
          cd seqan3
          git init .
          git remote add salsa https://salsa.debian.org/med-team/seqan3.git
          git fetch --depth 1 salsa
          git checkout salsa/debian/experimental -- debian

      - name: Install Dependencies
        working-directory: unstable/seqan3
        run: apt-get build-dep --yes --no-install-recommends . &>../apt.build-dep.log

      - name: Build
        working-directory: unstable/seqan3
        run: dpkg-buildpackage --unsigned-changes --unsigned-source --build=binary &>../seqan3.dpkg.log

      - name: Autopkgtest
        working-directory: unstable/seqan3
        run: autopkgtest ../seqan3*.deb ../libseqan3*.deb -- null &>../seqan3.autopkg.log

      - name: Delete Repo
        if: always()
        continue-on-error: true
        working-directory: unstable
        run: rm -fdr seqan3

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debian-seqan3-artifacts
          path: unstable
